# This is the camera-traps application configuration file.

title = "Camera-Traps Application Configuration"

[plugins]
internal = [
    "image_gen_plugin",
    "image_recv_plugin",
    "image_score_plugin",
    "image_store_plugin",
    "observer_plugin"
]
external = []
