# This is the camera-traps integration test configuration file.

iterations = 10
image_input_dir = "~/traps/input"
image_output_dir = "~/traps/output"

[external_plugin_config] 
    plugin_name = "ext_image_gen_plugin"
    id = "d3266646-41ec-11ed-a96f-5391348bab46"
    external_port = 6000
    subscriptions = [
        "PluginTerminateEvent"
    ]