# This is the camera-traps integration test configuration file.
# This file can be used directly by assigning its absolute path
# to the TRAPS_INTEGRATION_CONFIG_FILE environment variable.
# Alternatively, copying this file to ~/traps-integration.toml
# will also work.

iterations = 10
image_input_dir = "~/traps/input"

[external_plugin_config] 
    plugin_name = "ext_image_gen_test_plugin"
    id = "d3266646-41ec-11ed-a96f-5391348bab46"
    external_port = 6000
    subscriptions = [
        "PluginTerminateEvent"
    ]