# This is the camera-traps integration test configuration file.
# This file can be used directly by assigning its absolute path
# to the TRAPS_INTEGRATION_CONFIG_FILE environment variable.
# Alternatively, copying this file to ~/traps-integration.toml
# will also work.

# The number of times an image is injecting into the application.
iterations = 10

# The directory that must contain at least on image.
image_input_dir = "~/traps/input"

# The external plugin configuration for the integration test
# program.  The program acts like typical external plugins except
# that it only writes events to its TCP socket, it does not read
# any events.
[external_plugin_config] 
    plugin_name = "ext_image_gen_test_plugin"
    id = "d3266646-41ec-11ed-a96f-5391348bab46"
    external_port = 6000
    subscriptions = [
        "PluginTerminateEvent"
    ]