version: "3.0"

services:
  # the name `engine` is important here; in general, the sevice name is addressable by other conatiners on the same
  # docker network. The default "hostname" used by the python plugin library (pyevents) is "engine"
  engine:
    container_name: engine
    image: tapis/camera_traps_engine
    network_mode: host
    environment:
      - TRAPS_CONFIG_FILE=./traps.toml
    volumes:
      # mount the traps.toml in the current working directory.
      - ./traps.toml:/traps.toml:ro

